export const questions = [
  { q: 'At a party do you:', a: ['Interact with many, including strangers', 'Interact with a few, known to you'] },
  { q: 'Are you more:', a: ['Realistic than speculative', 'Speculative than realistic'] },
  { q: 'Is it worse to:', a: ['Have your “head in the clouds”', 'Be “in a rut”'] },
  { q: 'Are you more impressed by:', a: ['Principles', 'Emotions'] },
  { q: 'Are more drawn toward the:', a: ['Convincing', 'Touching'] },
  { q: 'Do you prefer to work:', a: ['To deadlines', 'Just “whenever”'] },
  { q: 'Do you tend to choose:', a: ['Rather carefully', 'Somewhat impulsively'] },
  { q: 'At parties do you:', a: ['Stay late, with increasing energy', 'Leave early with decreased energy'] },
  { q: 'Are you more attracted to:', a: ['Sensible people', 'Imaginative people'] },
  { q: 'Are you more interested in:', a: ['What is actual', 'What is possible'] },
  { q: 'In judging others are you more swayed by:', a: ['Laws than circumstances', 'Circumstances than laws'] },
  { q: 'In approaching others is your inclination to be somewhat:', a: ['Objective', 'Personal'] },
  { q: 'Are you more:', a: ['Punctual', 'Leisurely'] },
  { q: 'Does it bother you more having things:', a: ['Incomplete', 'Completed'] },
  { q: 'In your social groups do you:', a: ['Keep abreast of other’s happenings', 'Get behind on the news'] },
  { q: 'In doing ordinary things are you more likely to:', a: ['Do it the usual way', 'Do it your own way'] },
  { q: 'Writers should:', a: ['“Say what they mean and mean what they say”', 'Express things more by use of analogy'] },
  { q: 'Which appeals to you more:', a: ['Consistency of thought', 'Harmonious human relationships'] },
  { q: 'Are you more comfortable in making:', a: ['Logical judgments', 'Value judgments'] },
  { q: 'Do you want things:', a: ['Settled and decided', 'Unsettled and undecided'] },
  { q: 'Would you say you are more:', a: ['Serious and determined', 'Easy-going'] },
  { q: 'In phoning do you:', a: ['Rarely question that it will all be said', 'Rehearse what you’ll say'] },
  { q: 'Facts:', a: ['“Speak for themselves”', 'Illustrate principles'] },
  { q: 'Are visionaries:', a: ['somewhat annoying', 'rather fascinating'] },
  { q: 'Are you more often:', a: ['a cool-headed person', 'a warm-hearted person'] },
  { q: 'Is it worse to be:', a: ['unjust', 'merciless'] },
  { q: 'Should one usually let events occur:', a: ['by careful selection and choice', 'randomly and by chance'] },
  { q: 'Do you feel better about:', a: ['having purchased', 'having the option to buy'] },
  { q: 'In company do you:', a: ['initiate conversation', 'wait to be approached'] },
  { q: 'Common sense is:', a: ['rarely questionable', 'frequently questionable'] },
  { q: 'Children often do not:', a: ['make themselves useful enough', 'exercise their fantasy enough'] },
  { q: 'In making decisions do you feel more comfortable with:', a: ['standards', 'feelings'] },
  { q: 'Are you more:', a: ['firm than gentle', 'gentle than firm'] },
  { q: 'Which is more admirable:', a: ['the ability to organize and be methodical', 'the ability to adapt and make do'] },
  { q: 'Do you put more value on:', a: ['infinite', 'open-minded'] },
  { q: 'Does new and non-routine interaction with others:', a: ['stimulate and energize you', 'tax your reserves'] },
  { q: 'Are you more frequently:', a: ['a practical sort of person', 'a fanciful sort of person'] },
  { q: 'Are you more likely to:', a: ['see how others are useful', 'see how others see'] },
  { q: 'Which is more satisfying:', a: ['to discuss an issue thoroughly', 'to arrive at agreement on an issue'] },
  { q: 'Which rules you more:', a: ['your head', 'your heart'] },
  { q: 'Are you more comfortable with work that is:', a: ['contracted', 'done on a casual basis'] },
  { q: 'Do you tend to look for:', a: ['the orderly', 'whatever turns up'] },
  { q: 'Do you prefer:', a: ['many friends with brief contact', 'a few friends with more lengthy contact'] },
  { q: 'Do you go more by:', a: ['facts', 'principles'] },
  { q: 'Are you more interested in:', a: ['production and distribution', 'design and research'] },
  { q: 'Which is more of a compliment:', a: ['“There is a very logical person.”', '“There is a very sentimental person.”'] },
  { q: 'Do you value in yourself more that you are:', a: ['unwavering', 'devoted'] },
  { q: 'Do you more often prefer the:', a: ['final and unalterable statement', 'tentative and preliminary statement'] },
  { q: 'Are you more comfortable:', a: ['after a decision', 'before a decision'] },
  { q: 'Do you:', a: ['speak easily and at length with strangers', 'find little to say to strangers'] },
  { q: 'Are you more likely to trust your:', a: ['experience', 'hunch'] },
  { q: 'Do you feel:', a: ['more practical than ingenious', 'more ingenious than practical'] },
  { q: 'Which person is more to be complimented – one of:', a: ['clear reason', 'strong feeling'] },
  { q: 'Are you inclined more to be:', a: ['fair-minded', 'sympathetic'] },
  { q: 'Is it preferable mostly to:', a: ['make sure things are arranged', 'just let things happen'] },
  { q: 'In relationships should most things be:', a: ['re-negotiable', 'random and circumstantial'] },
  { q: 'When the phone rings do you:', a: ['hasten to get to it first', 'hope someone else will answer'] },
  { q: 'Do you prize more in yourself:', a: ['a strong sense of reality', 'a vivid imagination'] },
  { q: 'Are you drawn more to:', a: ['fundamentals', 'overtones'] },
  { q: 'Which seems the greater error:', a: ['to be too passionate', 'to be too objective'] },
  { q: 'Do you see yourself as basically:', a: ['hard-headed', 'soft-hearted'] },
  { q: 'Which situation appeals to you more:', a: ['the structured and scheduled', 'the unstructured and unscheduled'] },
  { q: 'Are you a person that is more:', a: ['routinized than whimsical', 'whimsical than routinized'] },
  { q: 'Are you more inclined to be:', a: ['easy to approach', 'somewhat reserved'] },
  { q: 'In writings do you prefer:', a: ['the more literal', 'the more figurative'] },
  { q: 'Is it harder for you to:', a: ['identify with others', 'utilize others'] },
  { q: 'Which do you wish more for yourself:', a: ['clarity of reason', 'strength of compassion'] },
  { q: 'Which is the greater fault:', a: ['being indiscriminate', 'being critical'] },
  { q: 'Do you prefer the:', a: ['planned event', 'unplanned event'] },
  { q: 'Do you tend to be more:', a: ['deliberate than spontaneous', 'spontaneous than deliberate'] },
];

export const firstLetter = [1, 8, 15, 22, 29, 36, 43, 50, 57, 64];
export const secondLetter = [2, 3, 9, 10, 16, 17, 23, 24, 30, 31, 37, 38, 44, 45, 51, 52, 58, 59, 65, 66];
export const thirdLetter = [4, 5, 11, 12, 18, 19, 25, 26, 32, 33, 39, 40, 46, 47, 53, 54, 60, 61, 67, 68];
export const fourthLetter = [6, 7, 13, 14, 20, 21, 27, 28, 34, 35, 41, 42, 48, 49, 55, 56, 62, 63, 69, 70];
